package com.sigebi.security.enums;

public enum RolNombre {
	ROL_USUARIOS,
	ROL_ABM_USUARIO,
	ROL_STOCK,
	ROL_ABM_STOCK,
	ROL_REPORTES,
	ROL_REPORTE_LISTADOS,
	ROL_PROCEDIMIENTOS,
	ROL_ABM_PROCEDIMIENTO,
	ROL_PERSONAS,
	ROL_ABM_PERSONA,
	ROL_PACIENTES,
	ROL_ABM_PACIENTE,
	ROL_ODONTOLOGIA,
	ROL_FUNCIONARIOS,
	ROL_ABM_FUNCIONARIO,
	ROL_ENFERMERIA,
	ROL_CONSULTORIO,
	ROL_CONFIGURACIONES,
	ROL_ABM_CONFIGURACION,
	ROL_CLINICA_MEDICA,
	ROL_ADMIN,
	ROL_AYUDA,
	ROL_ABM_AYUDA	
}
